name: Terraform setup
run-name: Terraform setup
on: [push]

env:
  TF_VERSION: "1.3.7"
  TF_DIR_GCP_ON_PREM_BASE: "terraform/gcp-base"

jobs:
  terraform:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          create_credentials_file: "true"
          workload_identity_provider: ${{ secrets.GCP_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_SA_ORG_EMAIL }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # GCP Base
      - name: Run terraform init for GCP Base
        working-directory: ${{ env.TF_DIR_GCP_ON_PREM_BASE }}
        run: |-
          terraform init
      - name: Run terraform validate for GCP Base
        working-directory: ${{ env.TF_DIR_GCP_ON_PREM_BASE }}
        run: |-
          terraform validate
      - name: Run terraform plan for GCP Base
        working-directory: ${{ env.TF_DIR_GCP_ON_PREM_BASE }}
        run: |-
          terraform plan -out=plan_output

      - name: Run terraform apply for GCP Base
        working-directory: ${{ env.TF_DIR_GCP_ON_PREM_BASE }}
        if: github.ref == 'refs/heads/main'
        run: |-
          terraform apply plan_output
